### ISSUE TITLE
Language Problem

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#10]
Issue: waghty too bg change faction mishi miri horde , dg chat barat baste msihe... ! 
(you cant speak that language)
ham too bg..
ham bade bg..
ta log koni fix she.

**Comment by D4R4** [comment]
nemitunam shabih sazi konam, sharayete emalesho kamel tozih bedid plz

**Comment by evil-mugetsu** [comment]
har dafe etefagh nemiofte wase ineh nemitooni ,
ama bazi waghta change faction ke mishi (aliance - horde)(horde - aliance)
dg nemitooni chat koni che too /s che /g che /w wa...

**Comment by D4R4** [comment]
In chiza random ya ba chance nist, inke dar che surat va tahte che sharayeti in etefagh miofte paye shoma ;),, agar kashf shod haminja pm bedid man reopen konam ;)

Edit: rasti TOP ACHIEVEMENT am be safheye aslie site ezafe shod wotlk.bliz.ir
50% oghat Top Achive ro neshun mide 50% top PlayTime, random e, refresh koni momkene avaz she
