### ISSUE TITLE
Mass dispell

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#100]
mass dispell priest too arena ya duel buff haii mesle divine paladian ya ice block mage ro barnemidare
wa bayad betore spam hadaghal 4 - 5 bar use dade she ta amal kone...

**Comment by D4R4** [comment]
Disspel nashodan Divine Sheild paladin ye meghdarish be khatere talent Stoicism shakhe Protection hast, dorost dare kar mikone,, 30% chance mide ke dispell nashe tu rank 3,,

Ice Block mage am be nazar fix miad, agar sharayet khasie ke spello bug mikone begin dobare open konam
