### ISSUE TITLE
black qiraji battle tank chain quest

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#101]
bad az complete kardane Q "The Might of Kalimdor” bayad betooni ba dragon mojood too tanaris ke Q ro tahvil migire sohbat koni wa oon behet scepter ro bede(  Rewards: The Scepter of the Shifting Sands http://www.wowhead.com/quest=8742/the-might-of-kalimdor ) (Dragone gozineii ro nadare ke beshe bahash sohbat kard ke behet scepter o bede)

bad az oon bayad portal ro baz koni wa Q akhar ro ke "Bang A Gong!" 
( http://www.wowhead.com/quest=8743/bang-a-gong ) hast ro be rahaty com koni wa mount ro begiri ama npc in Q , q ro nemide behet wali q badisho behet mide
Once you bang that gong go back to get that legendary mount.

ps : http://upload7.ir/uploads//cf32fa5e07c6cbaac7de7d507c4772c70e938f20.jpg

**Comment by D4R4** [comment]
fixed,gz
