### ISSUE TITLE
Quest  Bang a Gong!

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#102]
Quest  Bang a Gong! az ro Npc bardashte shode , Mesle zamani e ke yeki Mount o To server Gerefte Bashe , Quest ghabli va Badisho mide ini ke bayad mount o bede ro nemide !
http://www.wowwiki.com/Quest:The_Might_of_Kalimdor
http://www.wowwiki.com/Quest:Bang_a_Gong!

**Comment by D4R4** [comment]
fixed,gz

**Comment by Vengeans** [comment]
Tnx
