### ISSUE TITLE
 The Scepter of the Shifting Sands

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#103]
Q mount fix shode ama  [The Scepter of the Shifting Sands] fix nist !
bad az Q the might of kalimdor dragone tanaris (anachronos) bayad betooni bahash sohbat koni ta  Scepter ro behet bede , hata age 10 h war tamoom shode bashe wo mount ro gerefte bashan too server in npc bayad Scepter ro bede ama dg ghabele tahvil nemishe....

**Comment by D4R4** [comment]
fxied
