### ISSUE TITLE
 [Glyph of Succubus] Lock 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#109]
Be gofte yeki az player a  In Glyph o ke mziani Kiss pet Warlock Zamani ke Ro target mire bayad Shadow Classhai  mesle Priest O  Dis kone . Etelate  bishtar o mitonin az khode palayer begirin (Esme Player Abyss) .

**Comment by D4R4** [comment]
source bde, zaheran ke nabayad intori bashe,

**Comment by D4R4** [comment]
fixed
