### ISSUE TITLE
Important issue

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#11]
Issue: Too ye location i too Sholazar waghty ke mimiri hamoon sanie ress mishi .. !
sarfe nazar az inke chand bar poshte sare ham bemiri 2 min time waiting i wojood nadare wase ress shodan wo jadidan ham bazi az player haie horde az in bug wase bala bordane lifetime eshoon esfade mikonan.
(ba in ravesh mishe too har 10 min nazdik be 500 honorable kill jam kard)

**Comment by D4R4** [comment]
Fixed
