### ISSUE TITLE
Enchant Back Tiloring 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#111]
Enchanti Ke Ba Tiloring Ro Back MIzani Bedone inke Combat shi use mishe , Savare mount use mishe ....

http://upload7.ir/uploads//f004d8c075d1a7532604bf57b08f76089b38528c.jpg

**Comment by D4R4** [comment]
key in etefagh miofte? manke natunestam test konam,

**Comment by Vengeans** [comment]
dara jan khodam test kardam sar khod use nemishe , vali nemidonam chera ro hero balackmagic chera ountori e , sare jash vasade use mishe ....

**Comment by Thundermoon** [comment]
ba Salam . in Etefagh 1 Etefaghe Kamelan Normal e agar Eshtebah nakonam Character Black Magic Bayad Warlock bashan Bad in Enchant Moghei Ke Buff e  [Fel Armor] Roe Ishon hast Hop mide Va On Hop Baes Active Shodane in Enchant mishe.

**Comment by Vengeans** [comment]
Savare mount am bod use mishod ....

**Comment by D4R4** [comment]
ba copy Blackmagic am test mikonam nemitunam shabihsazi konam moshkelo, test kon bebin ghashang tu che sharayeti intori mishe, az tu combat log che spelli Proc mishe ke baes faal shodan Enchant mishe,

**Comment by Thundermoon** [comment]
Dara jan On buff i ke to tasvir roshe ro mibini? [Fel Armor] on Buff 1heal Per Sec i mide be khodesh ke on heal e Baes Active shodane in Enchant mishe va hich moshkeli nadare

**Comment by Thundermoon** [comment]
on Buff Fel Armor i ke Roshe Behesh Heal per Sec mide Va In Baes e Active shodane Enchant mishe!!
Fixesh am Hamine .!

**Comment by D4R4** [comment]
Invalid, closing
