### ISSUE TITLE
Event  [For The Children]

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#112]
Quest  [80] [Home Of The Bear-Men] Npc e NIst

http://www.wowwiki.com/Quest:Home_Of_The_Bear-Men

**Comment by Vengeans** [comment]
In 2 ta am bug an 
 [Hch'uu and the Mushroom People] 
[Visit the Throne of the Elements]

**Comment by evil-mugetsu** [comment]
fixed !
