### ISSUE TITLE
Nazarat Dar Morede Server

### ISSUE THREAD

**Issue by Thundermoon** [D4R4/BlizWoW#113]
Dar Inja Mikham harki ke dakhele Forum Hastesh Biad O Nazarat (Pishnehadat/Enteghadat) Esho Dar Morede Server Bege.

**Comment by Vengeans** [comment]
Server Az Nazare Modiriyat Sathesh Kheli Paine :(((

**Comment by Thundermoon** [comment]
Enshalah ke dorost mishe Bishtar az hame Modiriat Badesh Net e Server Kheili moheme in 2ta

**Comment by evil-mugetsu** [comment]
Inja wase Report wo announce fix shodane Issue hast , ja in topc too anjomane site e : 
http://forum.bliz.ir
