### ISSUE TITLE
 [80] [Collection of Goods](Part 2)

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#115]
Quest Class paldin e Item Quest  (Stratholme Holy Water) Nemishe Loot kard 
http://www.wowhead.com/quest=7642/collection-of-goods
http://www.wowhead.com/object=181085/stratholme-supply-crate#contains

**Comment by D4R4** [comment]
check shod, dorost kar mikone, mishe loot kard :| dobare test plz
