### ISSUE TITLE
Achivement Player vs Player , { The Justicar }

### ISSUE THREAD

**Issue by Rubmytotem** [D4R4/BlizWoW#117]
Reputation With Silverwing Sentinels >Dalile Kam dadane xP Injaro begin . ya Kheyli kam mide Xp Rep ya aslan Nemide .. ! Fix konin Tnx .. !

**Comment by D4R4** [comment]
Bayad FLag cap konid, normal e ke tul mikeshe, karish nemishe kard ;)
