### ISSUE TITLE
the forge of souls

### ISSUE THREAD

**Issue by alonee** [D4R4/BlizWoW#14]
boss 1 fos buge.orb ke mide biron kar nemikone buge
http://www.wowhead.com/npc=36497

**Comment by D4R4** [comment]
yekam vazehtar tozih bedid plz,, npc ro motevajeh shodam, moshkel ro na daghigh

**Comment by alonee** [comment]
boss 1 ke shoro mishe soul mikeshe bayad azash dor shi vagrna hp boss por mishe bad orb mide bayad ono bezani ta be boss narese age berese baz hp por mishe ke 2tasham bugan...

**Comment by D4R4** [comment]
Fixed
