### ISSUE TITLE
Extreme dp rate

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#15]
Issue : Northland Normal Dungeons item dp rates are Too high !
For example : Azjol-Nerub : dp Arctic Fur,boren leather,  (can solo the mobs , each 3 or 4 one of them drops 1x artic even without having skining skill )
example 2 : Utgarde pinnacle : dp too many blue quality Items wich you can disenchant them all into Dream Shards.
and Other ones ...

**Comment by D4R4** [comment]
Felan ba strategy server hamkhuni dare, khodemun in karo kardim custom hast,
