### ISSUE TITLE
Battleground

### ISSUE THREAD

**Issue by alonee** [D4R4/BlizWoW#17]
vagti ke join bg midi horde ya aliance mishi...
join bg dadani bazia ham digaro invite mikonan bad join as party midan ke to bg baham mishan intori ye taraf gavi mishe ye taraf na.age mishe to on halatam az ham joda shan ta ta'adol bargarar she!

**Comment by D4R4** [comment]
Ba guild mastera ye jalase mizarim hatman dar barash sohbat mikonim, in anjamesh kari nadare vali bayad raye aksariat bashe ke player shaki nashe,,

**Comment by evil-mugetsu** [comment]
Req ajibi darin , be shakhse tarjih midam ba friend ham play bedam .
be nazaram change faction ham nabayad bashe che bere3 be in kar...
