### ISSUE TITLE
Professor Putricide Problem

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#2]
issue : Red ozze charging on main tank (wiped the Raid instantly)
time & Date occured : 31 jan 2015  01:00 am (Icc 10 heroic) .

It was the first time ive seen this !@#$ on the server and i was like: its impossible   :|

**Comment by D4R4** [comment]
Closed, ta inke ba sharayet moshakhas dobare report she

**Comment by evil-mugetsu** [comment]
Happened again last night (3 Feb)(10hc) .
ba in tafavot ke ba charge kardane ozze roo main tank ke khodam boodam Raid wipe nashod , wo ba move dadan oftad.
