### ISSUE TITLE
Bug Mohem GunShip

### ISSUE THREAD

**Issue by mojtaba-viscky** [D4R4/BlizWoW#20]
Boss Dakhel gun ship  Harif ta dakhel Keshti ma miumad va Dps midad Ke nabaid biyad, moshkel Mohem baid sari tar fixesh konin 
Link Wowhead : http://www.wowhead.com/object=201873/gunship-armory
Name boss::For Aliance: High Overlord saurfang _ Hord:Muradin Bronzebeard

**Comment by D4R4** [comment]
in script Muradin e
http://puu.sh/fLMap/a1d1651276.png
faghat target ro tu keshti khodeshun mizane MAGAR INKE "NPC_KOR_KRON_REAVER" ya "NPC_KOR_KRON_SERGEANT" bashan, tu in mavaghe miad keshti moghebel va unaro mizane,
alan tu keshti moghabel be player attack mide?

**Comment by evil-mugetsu** [comment]
are , bad har chand sanie yekbar ham agro yeki dg mishe ba 99 stack !
akhare karam waghty ship e enemy miofte tank wo chand nafar dg ke boss beheshoon atack dade jaie DB sum mishan wo nemitoonan item ha ro loot konan ( too grup ha maloom nemishan ! )

**Comment by D4R4** [comment]
1) morde ya zende summ mishan?
2) tu masterloot list dge nistan fgahat?
3) boss ghashang tu keshti doshman attack sefid mide mikoshe playero?

**Comment by mojtaba-viscky** [comment]
Masalan ma ke Aliance hastim vaghti boss o Start midim Mage miad, Boss (Hord High Overlord saurfang ) Mire ro tank Dps ha miran Mage ro mizanan ta Inja hamechi Doroste BAd ke MAge Miofte tank va dps ha bar migardan be Keshti Khodemon bad Boss  (Hord High Overlord  hamrahe tank miad to keshti Khodemon ke nabaid biad boss Oun lahze baid bargarde sare jash vali.. bad khayli sari 99ta Stuck migire ke age tunt to tunt nakonim khayli sari hamaro tak mikone va raid Wip mishe ... Bug khayli vazehi has mitonin ba start Player ha sare boss Bebinin vaziato..

**Comment by mojtaba-viscky** [comment]
Dar zemn Player ha Morde sum mishan ro Portal

**Comment by D4R4** [comment]
ancient issue, closing
