### ISSUE TITLE
Bug Ins ice Crown

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#22]
1)Sare bone storm boss loardmarrorwar Felame ro hava mirize 
2)sare battel gunship boss ship doshman zamani ke player  br migardan ship khodeshon boss ham miad stack 99x mishe ...va loot boss hai az ghabli gun ship va Db bug mishe (vase bazi az palyer ha item sul mishe).
3) boss Rotface zamani ke spere mirize to raid kole raid o damage mide (boss ro be raid bar migarde poshtesh bo miri baz ham damage mikhori) va inke kole fight pore spel mishe engar dari try boss prof midi ye abom kam dare :)
4)boss Prof cast Ooz a zaheran moshkel daran va faz 3 player a mdps moshkel rang daran 
5) Damage Aoe class ai ghabile war dk paldin saer tomb boss sinder nemikhore 
6) damage aoe paladin sare boss Db ba inke add o target mikhori miad pain nazdik 3500 damage done o miare pain 
ba tashakor  vengeace

**Comment by D4R4** [comment]
1) fixed
2) az #20 peigiri konid, moshkel loot ham bayad daghigh bebinid az kojast khodetun bad report konid,
3) fixed
4) hamuntori ke #2 goftam ehtiaj be etelaat bishtar dare
5) DARE RUSH KAR MISHE, YE ISSUE FAGAHT BARAYE HAMIN DOROST KON PLZ
6) dorost kar mikone http://puu.sh/fLOLp/84df74a165.jpg dalilesh ine (aura)

*\* Etelaat bishtaro baraye har moshkel ye issue joda dorost kon + esmesh ham marbut be esm bashe yejuri ke tu search ya list moshakhas bashe harkodum male chie,,
