### ISSUE TITLE
Dungeons bug

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#24]
Issue 1 :  [Brann Spankin' New]
Issue 2 :  [Hadronox Denied]
dowomie ro gofte boodi fix kardi ama fix nashode , zire 8 sanie oftad hich kari natoonest kone ama bazam ....

**Comment by Vengeans** [comment]
[Brann Spankin' New] bug nist , Vase gereftan in Achive yekiton ghable inke Brann bere zir dasgah berre jolo ta damage bokhore (zaheran ye chizi ounja hast ke damage mide) .

**Comment by D4R4** [comment]
1) fixe
2) fix shode emshab update mishe

**Comment by Vengeans** [comment]
Ty FOr Fixeing
