### ISSUE TITLE
Spirit of Ar'tor 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#25]
Npc Spirit of Ar'tor Edame Quest o Nemide . 

http://www.wowhead.com/quest=10537/lohngoron-bow-of-the-torn-heart

Lotfan in Npc o dar Arae vaght fix konin Ke Ehtemal ghavi Quest ae badi sham bug dare :)

Ba Tashakor Vengeance

**Comment by Lumber-Jack-2** [comment]
problem is to find out which stuff sets you in another phase. in tbc there were no phasing on tc and blizz.

**Comment by D4R4** [comment]
SAI is a huge pain the my ass, will probably fix it someday tho, but I remeber I fixed it a while ago but the following quests in the chain were all broken,so someday,_figers crossed_

@Rushor Thank you very much to spare your time on my own little local issuetracker :) If it's not too much can I have your skype plox?

**Comment by Lumber-Jack-2** [comment]
i don't use skype but i am nearly always in this tc rizon chat ^^
http://collab.kpsn.org/display/tc/IRC

i used:

``` sql

DELETE FROM `spell_area` WHERE `spell`=59073 AND `area`=3752;
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES
(59073, 3752, 0, 10528, 0, 0, 2, 1, 1, 74);
UPDATE `creature` SET `phaseMask`=3 WHERE `id` IN (19802, 21656, 19799, 19800, 21292, 21337, 21309, 21928);
DELETE FROM `creature` WHERE `guid`=3106956 AND `id`=21318;
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`) VALUES 
(3106956, 21318, 530, 1, 2, 0, 0, -3801.27, 2599.23, 90.1398, 5.91756, 300, 0, 0, 6986, 0, 0, 0, 0, 0);
```

it works well, but it will never be acepted on tc ^^

**Comment by D4R4** [comment]
woot thanks :+1: 
all hail the DB King

**Comment by Vengeans** [comment]
Thank you for fixing
