### ISSUE TITLE
FOS Boss Spell

### ISSUE THREAD

**Issue by Ali-CFD-Alex** [D4R4/BlizWoW#26]
1.Boss Bronjahm [http://www.wowhead.com/npc=36497/bronjahm]
2.Spell Soulstorm [http://www.wowhead.com/spell=68872]
Mishe Cast Boss o ba Pummel warr cancel kard

**Comment by D4R4** [comment]
1) daghigh chie moshkel? tu che fazi? che moghe fight? kodum spell?
2) fixed

**Comment by evil-mugetsu** [comment]
fixed .
