### ISSUE TITLE
 [I Pitied The Fool]

### ISSUE THREAD

**Issue by AdmiralKunkka** [D4R4/BlizWoW#27]
in achieve Event buge !

**Comment by D4R4** [comment]
Invalid, achieve salem kar mikone (baraye ghesmat Wintergrasp tuye group(raid) va dargir fight nabashid, tarjihan tu otaghe VoA test konid)
EDIT: test shod ru kuhaye doro atrafam mishe gereft male Wintergrasp ro, faghat tu zone bashid va tuye fight nabashid,

**Comment by AdmiralKunkka** [comment]
to khode wintergrasp budam ! na to Group budam na To fight ! taghriban jelo Fortress budam ! vali sabz nashod !

**Comment by D4R4** [comment]
1) buy "Love Fool" from the vendor  www.wowhead.com/item=22261/love-fool
2) place it in the zone (wintergrasp)
3) use /pity on it (the emote)
4) profit?

**Comment by AdmiralKunkka** [comment]
migan Fix shode dara ! Ty az residegit ! Faghat alan monde in bossash k nistan to ins ! age inam dorost koni talas ! Mountesham 1 kam %esho biari bala khoda kheyret bede !

**Comment by D4R4** [comment]
hamash sob ok e
