### ISSUE TITLE
 [Lonely?]

### ISSUE THREAD

**Issue by AdmiralKunkka** [D4R4/BlizWoW#28]
In Achieve Event buge !

**Comment by AdmiralKunkka** [comment]
Mistake ! Fixed ! thx dara

**Comment by D4R4** [comment]
Ye iradai dare, report dadam be TC fix mikonan, hosele fix database nadaram midam una midan be baxeshun,

**Comment by AdmiralKunkka** [comment]
khodet beshin Eventaro fix koni behtare ! 1 bar dar sale har event ...

**Comment by D4R4** [comment]
hamechish alan ghabele gereftan ;) don't worry, manzuram ineke in Lonely? 100% blizzlike nist ba inke mishe gereft,
