### ISSUE TITLE
Death grip Them All !

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#3]
issue : Dk(dark knight) could death grip the boss !
time & Date occured : 31 jan 2015 17:00 pm on The Obsidian Sanctum (Sartharion)

**Comment by D4R4** [comment]
Moshkel hal shod, Tu RESTART badi emal mishe, 
Immune mask in NPC ha fix shod:
Sarathiron(28860,31311)
Vesperon(30449,31535)
Tenebron(30452,31534)
Shadron(30451,31520)

**Comment by AdmiralKunkka** [comment]
Agha Gj :+1:
