### ISSUE TITLE
bug hae Event  [Fool For Love]

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#30]
1) Boss Event Sum nashode 
2) Quest  [A Friendly Chat...] Bug dare 
3)Quest  [80] [Crushing the Crown] Bug dare

**Comment by D4R4** [comment]
1) summ shodan, vali SAI nadaran,(achive ina midan)
2) fix shod,
3) dar hale fix shodan...

**Comment by D4R4** [comment]
3) fixed
