### ISSUE TITLE
[Enchanting: Enchant Weapon - BLack Magic]on Dudu Feral/Rogue

### ISSUE THREAD

**Issue by Thundermoon** [D4R4/BlizWoW#33]
Ba Arze Salam O Khaste Nabashid Mikhastam 1moshkele Kocholo Ro Report konam Lazeme Ke Begam Enchanter Black Magic Tebghe Tajrobei ke dashtam Bayad Roe Class Haie melee Am Mesle Feral Dudu Ya Rogue Ya ... kar Kone alan AM 1link Az Servere madar Blizzard Beheton midam Ke To in Movie Kamelan Vazehe Ke Roe Dudu Feral Use Shode Enchant Esh 
http://www.warcraftmovies.com/movieview.php?id=205245 /Khoshhal Misham Residegi konid

**Comment by Thundermoon** [comment]
inam 1 Site e Motabar Dar morede in mOzoe http://www.wowhead.com/forums&topic=167534/bm-mongoose-berserking-question

**Comment by D4R4** [comment]
1) ruye rogue kar mikone (Instant Posison Proc)
2) ruye Druid faghat baraye Shred Mangle va Maul bayad kar kone ke fix shode va emshab emal mishe
http://www.wowhead.com/spell=59625/black-magic#comments
