### ISSUE TITLE
Anti Cheat [false positive catches]

### ISSUE THREAD

**Issue by Thundermoon** [D4R4/BlizWoW#36]
Ba Arze Salam va Khaste Nabashid Khedmate Admin/Fixer e Server e Blizz mikhastam begam in anti Cheat i ke gozashtid 1kam irad Dare vaghti Dis Mount Mikoni  migiratet Dar Bazi Az Mavaghe Charge am ke mikoni Migiratet Lotfan Residegi konid Mer30

**Comment by mojtaba-viscky** [comment]
Anti cheat Server Khayli bish az had hasase vaghti savar mount mishi Ye kam ke be zamin nezdik beshi Migirat bazi mavaghe dar hal rah raftan Anti cheat Eror mide bazi mavaghe vaghti Nitro Boot ya Shild Speed Pirist dade zade mishe Eror mide

**Comment by D4R4** [comment]
fixed,
