### ISSUE TITLE
[custom] Npc"s In Dalaran

### ISSUE THREAD

**Issue by Thundermoon** [D4R4/BlizWoW#37]
Ba Arze Salam o Khaste Nabashid e Dobare Khedmate St Team Fixxeri Bliz . Mikhastam 1nazari Dar Morede Npc Haie Ke To Dala Gozashtid Bedam Albate in Nazare Shakhsi e Bande Hast .
1.Be Nazare Bande Npc e Guild Rank ro Bardarid Behtare Chon be hich Dardi az nazare Bande Albate Nemikhore Faghat Baese Crash E Server Mishe 
2.in System i Ke Gozashtid Vase Online Bodan Khobe Vali Be nazare Man be Ravesh Haie Dg Mitonid Player haro Moshtagh be play To Server Konid hala To Payin 1chand Ta Rah Migam Ke Be Nazare Man Kheili Mitone Be Pishraft e Server Komak Kone.
n1:Mitonid Npc Shop Haie ke Gozashtid Item E Fun o ina mide ro 1kari konid Ke ba Badge of Justice ke to Ins/Df hc haie Lvl 70 ya hamon Bc(Burning Crusade) Mide Jay Gozin Konid Va ba In Kar Player haro ba Jaie AFk Kardan Be Ins haie Lvl 70 bebarid va 1kam Bishtar Beheshon Game Khosh Migzare
n2:1kar Dg am Mitonid Bokonid albate in 1kam Vaght Gire ama kheili Hal mide Masalan Blizzard Toe har realm esh hodode  3ta EM(Event Master)  Dare ke in EM ha Event haie Jalebi Bar Gozar Mikonan Dakhele Realm Va be Winner hash Reward Haie Mesle Pet o item e Fun midan Shoma Ham mitonid 1EM biarid Va Event Haie Mesle(Chair Event o Hide &Seek) Event O bar Gozar Konid 
Mamnon MIsham Age Residegi konid Va Nazare Khodetono Dar Morede in Post Bedid

**Comment by evil-mugetsu** [comment]
1 bardashte shod .
raje be system online ham dar anjoman bahs konid ta be ye natije beresim .
