### ISSUE TITLE
Halion 10 heroic

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#38]
waghty fight halion b phase 3 mire , wa kasaii ke too realm shadow hastan mian be fire..
halion ba umadane oona be fire ba inke na dps midan na heal wo faghat sai mikonan jaie khodeshoono fix konan, khod be khod az agro 100% mire rooshoon.
(\* fek konam age tanke fire ham too pahse bere realme shadow in moshkel etefagh naiofte , ama waghty too fire montazer bemoone ta boss biad intori mishe)

**Comment by D4R4** [comment]
yekam vazehtar tozih bde plz

**Comment by AdmiralKunkka** [comment]
Dara faze 1 rad mishe hame miran to Shadow ! boss k 50 % mishe onayi k mikhan bargardan to Fire ,kasi ke aval biad Boss Agro mishe Ro nafare avali k Omade to Fire ! Dar sorati k 1 tank kolan to fire bude ! moshkelesh ine ...

**Comment by evil-mugetsu** [comment]
daghighan , hala na faghat nafare aval..
age groupi ke bayad bian fire sari bian hadaghal roo 2 nafar mipare wo agro mishe .. !

**Comment by D4R4** [comment]
Ba inke tank tu kole phase 2 gereftatesh koli agro jam karde vali baz boss mire tu attackerai ke taze umadan? Aggrosh reset mishe yani engar avale fighte?

**Comment by evil-mugetsu** [comment]
are , ama phase 2 tank realm shadow boss ro migire.
tanke fire ya wai miste too realme fire , ya maid realme shadow dps mide
bahse ma waghty e ke hp boss 50 % mishe bar migarde realme fire ...
oon moghe harki az portal estefade mikone boss 100 % mire roosh sarfe nazar az inke 100 % agro tankie k gereftatesh

**Comment by Vengeans** [comment]
Aksare Server A hamin tori e , Tank ike biron Vasade Bayad havasesh bashe . Badesh hamin ke portal mide Boss am in var miad shoma chetor back mikonin portal ke boss aval ro shoma Agro mishe :)

**Comment by evil-mugetsu** [comment]
khob man tanke biroon wai mistam, kole cd hamam use mikonam ke ba agro bala bosso begiam ama har kari koni mire roo oon kasi ke t mikone az portal.
(age cloth poosh biad biroon tak mishe)

**Comment by D4R4** [comment]
Kheili khub gofti, intori report she asun fix mishe, working on it

**Comment by D4R4** [comment]
fixed, threat boss reset mishe tu phase 3, (az phase 1 nemimune kesi tu listesh)
