### ISSUE TITLE
Ice Crown gunship Problem

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#4]
good job Some lvels might not work like : dk death grip , paladin stun or sap , hunters trap and ...
but..
issue : As the Mage is being called out to freeze the ship you just need a Druid (feral or on the bear form) to cahrge on mage.
this will Stop him from casting and guns won't get frozen, and no more mages will spawn !
time & Date occured :Couple of Times , last time on 31 jan 2015 20:00 pm on ICC (25 nm)

**Comment by D4R4** [comment]
Feral Charge - Bear tasiri ruye NPC nadasht ehtiaj be fix nadasht,
Fera Charge - Cat mage ro bug mikard, fix shod,

Update badi emal mishe

Agar fix naghes hast badaz emal dobare replay bedin,,
