### ISSUE TITLE
Bug Sinder

### ISSUE THREAD

**Issue by mojtaba-viscky** [D4R4/BlizWoW#40]
sindergossa yki az boss haei hast ke Kolan ba Stuck ke ro Player ha mindaze raido tazeif Mikone Bug jadid server ye Jori shode ke vaghti Sinder player ha ro MArk mikone ta Ice beshan Ice ha Mes hava Mishan yni manzoram Inke mishe az to ice rad shod :| bana bar In Nemishe Player ha Stuck ha ro Poshte Ice khali konan va raid khayli zod Wip mishe Lootfan sari tar residegi konin

**Comment by D4R4** [comment]
fix shode, emshab mizaram
