### ISSUE TITLE
Bug Sinderagossa

### ISSUE THREAD

**Issue by mojtaba-viscky** [D4R4/BlizWoW#41]
Sinderagossa Yki az boss haei has ke Jadidan to server Bug shode , vaghti Sinder Player ha ro mark mikone Ice ha to khali mishe yani mishe az to ice rad shod va3 hamin Player ha nemitonan Stuck ro Poshte Ice khali konan dar natije raid zod wip mishe ... ice Sinder Be tore Koli Bug shode va to halet asli Khodesh nist

**Comment by evil-mugetsu** [comment]
Fixed.
