### ISSUE TITLE
fall damage problem

### ISSUE THREAD

**Issue by arashzgh** [D4R4/BlizWoW#44]
age too ye location berid savare mount shod ke ekhtelafe ertefa dashte bashe va ye ja berid ke auto dismount dashte bashe az ertefaE kam ham biyoftid fall damage mikhorid va mimirid

**Comment by D4R4** [comment]
location + coordinates + screenshot plz

**Comment by D4R4** [comment]
ye rah e bazsazi moshkel ro bayad baraye man begid ke beshe check kard

**Comment by D4R4** [comment]
ancient, closing
