### ISSUE TITLE
Moshkel Quest Hae Daily Server 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#49]
Quest Hae Daily Server Dar Bazi Az Roz ae Hafte Reset Nemishan Az Jomle Quest Ae Toc & Base Shollazr & Wintegrasb , Aksare Plyaer a Dar In Bare Ticket Mikonan Dar Sorat Emkan Residegi Konin

**Comment by D4R4** [comment]
fixed
