### ISSUE TITLE
What Do You Feed a Yeti, Anyway?

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#5]
Issue : Q bug "What Do You Feed a Yeti, Anyway?"
mishe item q ha ro rooye ship use dad , shark ha ham bala kashty zaher mishan !
waghty ham ke zire ab use mikoni bazi waghta shark ha be tahe ab miran wo bala nemian !
(bayad faghat beshe Item q ro too darya use kard)

**Comment by D4R4** [comment]
Moshkel BIRUN AB summ shodan fix shod,
Moshkel inke tahe ab mioftan visual hast, harjaye ab bashid move bedid NPC rutun aggro mikone, ehtiaji nist ke ta kafe ab berid,
