### ISSUE TITLE
Bug Bg Strand of the Ancients

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#51]
Tank Hae Mojod Dar In Bg Zamani Ke Tavasot Player ae Doshman  Damage Mikhore Az Tank Piyade Ke mishan Dobare savar mishan Hp Tank Full Mishe

**Comment by D4R4** [comment]
Source bedin ke nabayad intori bashe,

**Comment by D4R4** [comment]
Bad open mikonam

**Comment by Vengeans** [comment]
In bug kamakan fix nashode ,

**Comment by D4R4** [comment]
Ki gofte buge?! Source va fixesho biarin bebinam chie
