### ISSUE TITLE
moshkel Lag Server

### ISSUE THREAD

**Issue by mojtaba-viscky** [D4R4/BlizWoW#52]
LAg Server sare 25 man ha khayli shadid mishe Jori ke Kole raid lag mishan lootfan saritar Lago Fix konin Ply dadin to in halat va3 hame playera sarver sakhte che Ounaei ke lagan che Ounaei ke Fixan.. albate jadidan server khayli Crash mikhore Kolan Ping server balas

**Comment by AdmiralKunkka** [comment]
Lotfan Residegi konin ! Nemishe To in Lag Play dad ! in tanha moshkele  1ki  2 nafar nis .....

**Comment by poryademon1** [comment]
lotfan be moshkele lag va dc residegi shavad nemishe intori raid raft

**Comment by huntsman2** [comment]
Agha key mikhad Fix She in lage server ?! Bekhoda Injuri inja Fayde nadare haaaaa

**Comment by ijatim** [comment]
Age Server Haminjoor Lag Bashe Man Vaght Namizaram Alaki Ply Konam. Pls Sary Residegi Konid.

**Comment by deragonlord** [comment]
Are Kheyli kheyli Lage Residegi Konid Yani Chi Alaki Darim Vaght mizarim Ke chi Beshe Hadaghal Lago Fix KOnid crasho Fix KOnid Hamash Dc lag

**Comment by D4R4** [comment]
in hafte dge akhareshe, moshkel sakht afzari dasht antenamun hamaro avaz kardim,,
