### ISSUE TITLE
Mark Of The Fallen Champion

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#53]
Sare Boss Db Afradi Ke Roshon Mark Of The Fallen Champion Hast Bemiran Bade inke (Boss Kill) shode Res Am koni Baz Mark Rosh Mimone .(Yani ta boss badi rosh hast)
inam link SS a 
http://uupload.ir/files/g9jl_wowscrnshot_021815_130118.jpg
http://uupload.ir/files/idx_wowscrnshot_021815_132138.jpg
http://uupload.ir/files/begv_wowscrnshot_021815_133228.jpg
http://uupload.ir/files/geff_wowscrnshot_021815_135340.jpg

**Comment by D4R4** [comment]
link eshtebahe

**Comment by Vengeans** [comment]
Sorry 2bare link kardam

**Comment by D4R4** [comment]
code esh hast ke buff ro az ru target bardare bade inke DB mord, vali tavasote DB cast mishe va age LOS bashe ya dur bashe cast rush nemiofte,, , bemuneam Stinky sage Prof bar midare az ru raid
