### ISSUE TITLE
Boss <<Flame Leviathan>> Ulduar Vaghty Fight Shoro Mishe Az Combat Dar Miyad Dobare Healthesh Por Mishe

### ISSUE THREAD

**Issue by ijatim** [D4R4/BlizWoW#55]

**Comment by Vengeans** [comment]
In moshkel zamani pish miad ke taraf savare tank mishe bad miai az oun starter start mikoni 

bayad ghable inke savar tank shin leader raid start kone bad ......

Npc Start :  Lore Keeper of Norgannon

**Comment by D4R4** [comment]
moshkel ghadimi bude chand sal bude vali alan fix shode,, hamuntor ke goftan startesho bezanid ok e ;)
