### ISSUE TITLE
Moshkel Reward Time Online 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#60]
In Reward i ke be Time Online Talogh Migire Be Hero Bazi Az Player A Dade Nemishe Lotfan Dar Sorat Emkan Residegi konin

**Comment by D4R4** [comment]
Moshkeli az nazare codi ya az taraf server nist,, age player khassi tu sharayete khassi in moshkelo dare hatman begin dobare open konam,,

**Comment by D4R4** [comment]
in reportai ke BAZI VAGHTA etefagh mioftaro aval moshakhas konid tahte che shareytie bad report koninn ke beshe check kard,,

**Comment by D4R4** [comment]
EDIT: moshkel az code bud, fixed in next update(emshab farda)

**Comment by Vengeans** [comment]
Ty For FIxed
