### ISSUE TITLE
focus magic problem

### ISSUE THREAD

**Issue by arashzgh** [D4R4/BlizWoW#61]
focus magic mipare roo player vaghti off o on mishe ya vaghti player ja be ja local mishe masalan too RS vahgti miri portal focus magic root mipare .

**Comment by D4R4** [comment]
amalkard spell normal hast va bayad intori bashe, vaghti Source spell (mage,CASTER) ke ba crit target spell(TARGET) rush buff miofte agar dar range nabashe ya tuye yek phase dge az fight bashe spell az bein mire, ham buff crit TARGET ham proc chance e crit CASTER,Mage

**Comment by D4R4** [comment]
spell hai ke bond va link hastan dar surate nabud har 2 taraf anan az bein miran va check Proc ro rad nemikonan,,

EDIT: bugi ke ba retalent kardan hanuz Focus Magic ruye yar mimund va be mage CASTER proc midad ham fix shod,

http://puu.sh/g6d0i/e64b016537.jpg
