### ISSUE TITLE
ICC bug.....

### ISSUE THREAD

**Issue by Ali-CFD-Alex** [D4R4/BlizWoW#66]
Boss Rotface  vagti ke ozze Explosion mishe , to caste Explosion spell e CC e dudu cast o cancel mikone va ye joorai Explosion Divert mishe....

**Comment by Vengeans** [comment]
Cast Daskhat Mikhore Vali Spel o To Raid Mirize 
manzoram spel khode Ooz e bod na Spel boss , rasti say kardin spel boss o fix konin vali zaheran kamel moafagh nashodin  . ye moshkel dige am hast Ooz a dam be dam spel mirzan in am test konin

**Comment by D4R4** [comment]
Explosion e khode ozaro migana, check mikonam

**Comment by D4R4** [comment]
Fixed,
