### ISSUE TITLE
Moshkel Rang Mdps 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#69]
Sare Faz 3 Boss Prof Mdps & Tank ba Moshkel Rang movajeh Mishan . 
In Moshkel Tahadi e ke Tank & Dps mele Bayd Kamel Beran  Zir Boss Ke Dar In Sorat [Choking Gas Bomb] Migiran . Lotfan Residegi konin

**Comment by D4R4** [comment]
Fixed,

**Comment by Vengeans** [comment]
Ty For Residegi sari shoma
