### ISSUE TITLE
[Malleable Goo]

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#70]
Sare Boss Prof in [Malleable Goo] part mikone hamon bare aval ke zamin mikhore mahv mishe .

Aia in [Malleable Goo] Nabayesti Bade 3 Bar Zamin Khordan Mahv She ?

**Comment by Ali-CFD-Alex** [comment]
Na ! 3 bar Fix mikhore zamin Age kasi to hamoon bare aval Malleable Goo bokhore besh dg Mahv mishe

**Comment by D4R4** [comment]
Moshkel kamel vazeh nist, age proof o vido in dastana dashtin dobare open mikonam

**Comment by Vengeans** [comment]
Ohhh Man Be In nokte ke ali gofte tavajoh nakarde bodam , Eshtebah az man bode Fixe :}

Nake to raid ae ma hame alidaie an .... :)
