### ISSUE TITLE
Boss Blood Princes - Gunship Battel

### ISSUE THREAD

**Issue by Ali-CFD-Alex** [D4R4/BlizWoW#71]
BP = Kinetic Bomb o Bezani Nazani Mikhore Zamin miterke hamaro part mikone !

http://www.wowhead.com/spell=72052/kinetic-bomb
http://www.wowhead.com/npc=38454/kinetic-bomb

GSH = Age Mage o hamoon lahze ke Summon mishe CC koni ta akhare Fight Mage bug mishe....

A : http://www.wowhead.com/npc=37117/korkron-battle-mage

H : http://www.wowhead.com/npc=37116/skybreaker-sorcerer

**Comment by Vengeans** [comment]
MOshkel Kenetic Boom boss Bp Zamani e ke Boom Taghriban be 3Yardi zamin mirese vali fasele bish az in bashe Shadow rosh Bashe Be Zamin Nemirese

**Comment by Ali-CFD-Alex** [comment]
Na Kollam bug e ! Hunter moon az hamoon aval mizadesh baz mikhord zamin miterkid

**Comment by D4R4** [comment]
Part 1 ehtiaj be info dariM, ba source moshakhas bashe ke fixesh chejurie,
Part 2 fixes,,
