### ISSUE TITLE
Shop For Weapon

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#72]
To Server Ghabli Ye Shop For Weapon Vojod Dasht Ke Ba Honor & Arena Point Item Azash Migereftand , Age Emkanesh Hast Va Dar Sorat Salah Did ,Hamchi Shopi Dar Ekhtiyar Player Ae Server Gharar Dahid .

Ba Tashakor Vengeance

**Comment by D4R4** [comment]
hamun itema ezafe shod, agar fek mikoni ehtiaj be taghriat dare ghashang list kon pishnahade taghirato inja dune dune harchi lazeme ezafe konim
hamin zir mishe chatid

**Comment by Vengeans** [comment]
Haji laghal Esm & shelesho avaz mikardi , yechi bezar palyer o jazb kone :)
