### ISSUE TITLE
Duel Zone 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#73]
Age Emkanesh Hast Ye mantaghe vase Duel Doros Konin Va .b o vase ounja bezarin Fk konam Kheli Am Esteghbal Dashte bashe 

Ba Tashakor Vengeance

**Comment by Thundermoon** [comment]
Harfe Shoma Kamelan Sahihe Vali in kara Baes Sangin Shodane Data Base Mishe Va Natije Khobi nadare / Be Eteghade Bande Har Chizi Normal  bashe behtare ta chizi az khodemon behesh Estefade konim

**Comment by evil-mugetsu** [comment]
Closed !
