### ISSUE TITLE
Quest  [Azuregos's Magical Ledger]

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#74]
Npc Tahvil Quest Nist 

http://www.wowwiki.com/Narain_Soothfancy

http://wow.gamepedia.com/Quest:Azuregos's_Magical_Ledger

**Comment by D4R4** [comment]
chain quest haye Black Giraj Battletank ro khodemun bastim, ba delete kardan in npc

**Comment by Vengeans** [comment]
Okkkkkkkkk
Ghablesh maro dar jaryan mizashti :}
