### ISSUE TITLE
stackable buff

### ISSUE THREAD

**Issue by arashzgh** [D4R4/BlizWoW#78]
salam buff demonict pack lock ba toteme shaman stack nemishe faghat yekish miad too servere cata ya mop ya WOD bayad intori bashe vali too 3.3.5 jofte buff haye warlock demon (spell power ) va shaman elemental ( totem ) bayad roo raid bashe choon too cata joft buff hash yeki hast har do  10 % spell mide amma inja fargh dare lotfan residegi konid

**Comment by D4R4** [comment]
esm buffaro ba link wowhead bezarin

**Comment by D4R4** [comment]
check shod, nabayad stack she, mohem nist in addade un darsad, hardoshun az ye jensan, calculate mishe har kodum BISHTAR sp midad un asar mikone,, alanam hamintorie tu server 

more info here https://github.com/TrinityCore/TrinityCore/issues/4313
