### ISSUE TITLE
 [Hand of Protection] Sare Boss Prof

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#79]
Sare Ooz Hae Prof Zamani Faghat Ba Abom MIshe Slow shon kard Dalili Nadasht ke Biain  [Hand of Protection] Ro target o Imiumm koni , Hich yek az spel hae Class a Ro movement Ooz e Tasiri nemikonan . Dar zemn Achive   [Nausea, Heartburn, Indigestion... (25 player)] Dali bar ine ke Bayesti bedon abom Ooz o zad  Hala nemidonam ba   [Hand of Protection] ya Spel ae Class ae bayad Jori she ke Az residan Ooz be targe Gerefte she . alan ba in kari ke shoma kardin age Sare Chang faz a ye Ooz biad Raid fatalesh khonde mishe be Fekr Guid ai am bashin ke bedon Ts Raid  mizanan

**Comment by D4R4** [comment]
fixed
