### ISSUE TITLE
 [Defense of the Ancients]

### ISSUE THREAD

**Issue by AdmiralKunkka** [D4R4/BlizWoW#8]
In achieve  Strand of the ancients Buge !!!

**Comment by D4R4** [comment]
Achievement dorost kar mikone, ghabele gereftan hast, faghat sharayet khase khodesho dare
http://www.wowhead.com/achievement=2200/defense-of-the-ancients#comments
http://www.wowhead.com/achievement=1757/defense-of-the-ancients#comments
http://puu.sh/fkAqL/be445e504e.jpg

INVALID REPORT ****
