### ISSUE TITLE
pala prot

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#82]
dps paladian protection kheili low e..
ba ye negah be link haie zir rahat mishe fahmid pala prot dps kheili balaii bayad dashte bashe , ke hata beshe bahash pvp ply kard ama motesefane damage esh enghadar low hast ke dk ya war sare raid ha mitoonan ba zadane crit azash be rahaty agro begiran !

http://theworldofwarcrafters.blogspot.com/2013/01/pvp-paladin-protection-spec-guide-2v2.html#axzz3UCAmfcpd
http://forum.molten-wow.com/showthread.php?t=100423
http://eternal-wow.com/forum/redemption/protection-paladin-pvp-t83207.html
http://www.wowhead.com/forums&topic=106219/prot-dps-pvp-protribution-guide-updated-3-3
http://wow-na-wow.blogspot.com/2014/02/pvp-protection-paladin-talent-build-wow.html

"In WOTLK Prot paladins damage is insane it is amazing"
"but in 3.3.5, their burst damage and sustain made them even as good as viable (to a certain extent) in 2v2 arenas. "
wa....

yadame avaiele run shodane server ke damage ha az core molten bood , pala prot ham andaze ba bazi class ha dps balaii midad wo too recount hamishe balatar az bazi dps ha mishod.

**Comment by evil-mugetsu** [comment]
ba tavajoh be afzayeshe 5% damage done bazi class ha wa hamchenin damage besyar paiine pala prot fek konam hadaghal bayad 20-24 % damage esh bishtar beshe..

**Comment by D4R4** [comment]
#85
