### ISSUE TITLE
 Baltharus the Warborn

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#83]
Bos Baltharus the Warborn to map Rs zamani ke Copy mide , Copy e  aslan damagi be Target  nemide

**Comment by D4R4** [comment]
Fixed, Saviana Ragefire ham hamin moshkelo dasht, dorost shod

**Comment by Vengeans** [comment]
Tnx

**Comment by Vengeans** [comment]
Sare In boss Debuff  [Enervating Brand] Fix nist , Debuff o be nesfe raid mide
