### ISSUE TITLE
Ban Gm :{

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#88]
vaghan vase ye admin motaesfam ke sare ye ss i ke aslan nakhone Gm server esho ban karde . haji age dos nadri inja bashim rahat bego , dar kol ma inja kiret am nistim ,,,,,,,,,,,
http://upload7.ir/uploads//f696510f0095cddda6ed23166fadea4831dbf36f.png

**Comment by evil-mugetsu** [comment]
fek konam tanha kasi ke nemikhad shoma inja bashin khodetoon hastin , ba in raftar ha.
gm i ke khodesh gm i khodesho ban kone fek nakonam doost dashte bashe play bede oonam ghable in dastana..
server : vengeance has baned vengeance permanently reason : kir to wow

**Comment by Vengeans** [comment]
hehe

vagti gm high rank ejaze nemide gm ae ranke pain kareshun o anjam bedan dige arzeshi ndare ma bashim

**Comment by evil-mugetsu** [comment]
i know,
in moshkel rishash az arenast ke ejaze barkhod ba afradio ke tabani mikonan nadarim.

**Comment by D4R4** [comment]
adam baraye ye seri chiza tu bussiness esh risk nemikone, aval amal mikone ke az khesarat kam she bad porsoju mikone
