### ISSUE TITLE
City Defender

### ISSUE THREAD

**Issue by evil-mugetsu** [D4R4/BlizWoW#9]
Issue : bug boodane achive city defender
ba koshtane 50 random animals mesle ahoo , sanjab , khargoosh wa... too har kodoom az Home City ha mishe in achive ro be rahaty gereft !
(Des : Kill 50 "ENEMY" Player In Any Of Your Home City)

**Comment by D4R4** [comment]
Man nemitunam bazsazish konam, kamel tozih bedin chikar bayad bokonam ke counter esh bere bala, man Critter(ahoo,moosh,gorbe) haro mikosham 0/50 munde

**Comment by evil-mugetsu** [comment]
Fix shode , ghablan ba koshtane Critter ha counter bala miraft.
