### ISSUE TITLE
Two Jormungars  (toc)

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#90]
Sare in 2ta mini boss Range fix nist ,Two Jormungars  mian avale kar ouni ke move mikone rangesh fix e rahat mishe az flame move kard vali chang ke mishe nemishe flame o  move kard boss daqian michasbe be tank .

**Comment by D4R4** [comment]
fixed, combat_reach esh kam bud un model

**Comment by Vengeans** [comment]
Tnx For Fixed

**Comment by Vengeans** [comment]
Dara champion 25 o yekam low tar kon dada pls

**Comment by Vengeans** [comment]
Range Two Jormungars  hanoz fix nashode , boss e michsbe be tank .....
