### ISSUE TITLE
Dps PAladin Retri

### ISSUE THREAD

**Issue by mojtaba-viscky** [D4R4/BlizWoW#95]
Chand vaghte Ahsas mikonam sare raida Dps Paladin Lowe shode man Kolan 2 haftas daram To icc test mikonam Avael Server ba Paladin 5700 16k sare Db mizadam __ alan Ba Hamon Pala ba gs 6030 be zor 14k mizanam sare db Man ahsas mikonam Crit paladin Ba moshkel Movaje shode Lootfan ye Testi Bokonin ..

**Comment by Vengeans** [comment]
Kolan damge done pala chand vaqti e umade pain ... pala prot am ziyad tarifi  nadare nemishe agro gerft 
4sete Tier 10 pala fix e ?
