### ISSUE TITLE
Blackwing Lair 

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#97]
1) Boss Akhar In ins Bug e , Boss Nefarian sum ke mishe hamun bala mimone , Player a for Loot Quest Item Mount Murche MIran Ins Vali nemitonan boss o kill konan (zaheran boss kharej az map ins e ) Dar sorat emakn residegi konin Ty
http://upload7.ir/uploads//b8b5acbc0d744c3ba84019f9e93db5afddfb380d.jpg

2) Boss Broodlord Lashlayer  Leave Combat Mishe , Nemishe Killesh kard
http://upload7.ir/uploads//432ef4601c7df032fd03d18b281f6a65c10dad9a.jpg

**Comment by D4R4** [comment]
2) invalid https://github.com/TrinityCore/TrinityCore/issues/10449

1) almost fixed, working on it

**Comment by Vengeans** [comment]
Tnx For Fixed

**Comment by Vengeans** [comment]
Fix nashode !
2) Boss Broodlord Lashlayer Leave Combat Mishe , Nemishe Killesh kard
http://upload7.ir/uploads//432ef4601c7df032fd03d18b281f6a65c10dad9a.jpg
