### ISSUE TITLE
Arena (Pet Class Ha)

### ISSUE THREAD

**Issue by Vengeans** [D4R4/BlizWoW#98]
Sare Arena Pet Ha Sargije migiran , Jahai ke sako hast player ke mipare pain pet e gir mikone ya dore khodesh micharkhe . in moshke jahae dige am pish miad , sare Pos palyer az oun bala mipare pain pet mire dor mziane chata add am miare . dar sorat emkan residegi konin 

To arena hai ke sako ya pol daran in moshkel amone player haro boride

**Comment by D4R4** [comment]
screenshot bedin, har kodum dalile mokhtalef dare,kamel tozih bedin ok mikonam
